# Site settings
title: Nikon
client:
  name: Nikon
  link: https://www.europe-nikon.com/en_GB/
description: >
  Immerse yourself in effortlessly photogenic destinations with Secret Escapes and Nikon. We sent three Secret Escapes colleagues, passionate about photography, to learn more about what it takes to capture the perfect shot.
baseurl: "/nikon" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed