# Site settings
title: Nikon Home
client:
  name: Nikon
  link: "https://www.nikon.co.uk/en_GB/products/category_pages/digital_cameras/mirrorless/overview.page?utm_source=secret-escapes&utm_medium=cta-button&utm_campaign=secret-escapes-home"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Nikon and Secret Escapes found two photographers from opposite ends of the earth and brought them together for two unforgettable adventures – in turn, they were sent home. The pair explored Norway’s mesmerising Lofoten Islands, before heading to the urban sprawl of Singapore.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/nikon" # the subpath of your site, e.g. /blog/
img:     "/nikon/_assets/img"
css:     "/nikon/_assets/css"
js:      "/nikon/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
